version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: farm_postgres
    environment:
      POSTGRES_DB: farm_db
      POSTGRES_USER: farm_user
      POSTGRES_PASSWORD: farm_pass
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farm_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: farm_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - farm_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: farm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@farm.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - farm_network
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  farm_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: